export const FULL_LANGUAGE_MAPPING = [
  // A
  {
    iso_639_1: 'aa',
    iso_639_2: 'aar',
    iso_3166_1: 'ET',
    flag: '🇪🇹',
    english_name: 'Afar',
    name: 'Qafár af',
  },
  {
    iso_639_1: 'ab',
    iso_639_2: 'abk',
    iso_3166_1: 'GE',
    flag: '🇬🇪',
    english_name: 'Abkhazian',
    name: 'Аҧсуа бызшәа',
  },
  {
    iso_639_1: 'ae',
    iso_639_2: 'ave',
    iso_3166_1: 'IR',
    flag: '🇮🇷',
    english_name: 'Avestan',
    name: 'Avesta',
  },
  {
    iso_639_1: 'af',
    iso_639_2: 'afr',
    iso_3166_1: 'ZA',
    flag: '🇿🇦',
    english_name: 'Afrikaans',
    name: 'Afrikaans',
  },
  {
    iso_639_1: 'ak',
    iso_639_2: 'aka',
    iso_3166_1: 'GH',
    flag: '🇬🇭',
    english_name: 'Akan',
    name: 'Akan',
  },
  {
    iso_639_1: 'am',
    iso_639_2: 'amh',
    iso_3166_1: 'ET',
    flag: '🇪🇹',
    english_name: 'Amharic',
    name: 'አማርኛ',
  },
  {
    iso_639_1: 'an',
    iso_639_2: 'arg',
    iso_3166_1: 'ES',
    flag: '🇪🇸',
    english_name: 'Aragonese',
    name: 'Aragonés',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'SA',
    flag: '🇸🇦',
    flag_priority: true,
    english_name: 'Arabic',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'AE',
    flag: '🇦🇪',
    english_name: 'Arabic (UAE)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'EG',
    flag: '🇪🇬',
    english_name: 'Arabic (Egypt)',
    name: 'العربية',
  },
  {
    iso_639_1: 'as',
    iso_639_2: 'asm',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Assamese',
    name: 'অসমীয়া',
  },
  {
    iso_639_1: 'av',
    iso_639_2: 'ava',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Avaric',
    name: 'Авар мацӀ',
  },
  {
    iso_639_1: 'ay',
    iso_639_2: 'aym',
    iso_3166_1: 'BO',
    flag: '🇧🇴',
    english_name: 'Aymara',
    name: 'Aymar aru',
  },
  {
    iso_639_1: 'az',
    iso_639_2: 'aze',
    iso_3166_1: 'AZ',
    flag: '🇦🇿',
    english_name: 'Azerbaijani',
    name: 'Azərbaycan',
  },

  // B
  {
    iso_639_1: 'ba',
    iso_639_2: 'bak',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Bashkir',
    name: 'Башҡорт теле',
  },
  {
    iso_639_1: 'be',
    iso_639_2: 'bel',
    iso_3166_1: 'BY',
    flag: '🇧🇾',
    english_name: 'Belarusian',
    name: 'Беларуская мова',
  },
  {
    iso_639_1: 'bg',
    iso_639_2: 'bul',
    iso_3166_1: 'BG',
    flag: '🇧🇬',
    english_name: 'Bulgarian',
    name: 'Български език',
  },
  {
    iso_639_1: 'bi',
    iso_639_2: 'bis',
    iso_3166_1: 'VU',
    flag: '🇻🇺',
    english_name: 'Bislama',
    name: 'Bislama',
  },
  {
    iso_639_1: 'bm',
    iso_639_2: 'bam',
    iso_3166_1: 'ML',
    flag: '🇲🇱',
    english_name: 'Bambara',
    name: 'Bamanankan',
  },
  {
    iso_639_1: 'bn',
    iso_639_2: 'ben',
    iso_3166_1: 'BD',
    flag: '🇧🇩',
    flag_priority: true,
    english_name: 'Bengali',
    name: 'বাংলা',
  },
  {
    iso_639_1: 'bo',
    iso_639_2: 'bod',
    iso_3166_1: 'CN',
    flag: '🇨🇳',
    english_name: 'Tibetan',
    name: 'བོད་ཡིག',
  },
  {
    iso_639_1: 'br',
    iso_639_2: 'bre',
    iso_3166_1: 'FR',
    flag: '🇫🇷',
    english_name: 'Breton',
    name: 'Brezhoneg',
  },
  {
    iso_639_1: 'bs',
    iso_639_2: 'bos',
    iso_3166_1: 'BA',
    flag: '🇧🇦',
    english_name: 'Bosnian',
    name: 'Bosanski',
  },

  // C
  {
    iso_639_1: 'ca',
    iso_639_2: 'cat',
    iso_3166_1: 'ES',
    flag: '🇪🇸',
    english_name: 'Catalan',
    name: 'Català',
  },
  {
    iso_639_1: 'ce',
    iso_639_2: 'che',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Chechen',
    name: 'Нохчийн мотт',
  },
  {
    iso_639_1: 'ch',
    iso_639_2: 'cha',
    iso_3166_1: 'MP',
    flag: '🇲🇵',
    english_name: 'Chamorro',
    name: "Finu' Chamorro",
  },
  {
    iso_639_1: 'co',
    iso_639_2: 'cos',
    iso_3166_1: 'FR',
    flag: '🇫🇷',
    english_name: 'Corsican',
    name: 'Corsu',
  },
  {
    iso_639_1: 'cr',
    iso_639_2: 'cre',
    iso_3166_1: 'CA',
    flag: '🇨🇦',
    english_name: 'Cree',
    name: 'ᓀᐦᐃᔭᐍᐏᐣ',
  },
  {
    iso_639_1: 'cs',
    iso_639_2: 'ces',
    iso_3166_1: 'CZ',
    flag: '🇨🇿',
    english_name: 'Czech',
    name: 'Český',
  },
  {
    iso_639_1: 'cu',
    iso_639_2: 'chu',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Church Slavic',
    name: 'Словѣньскъ',
  },
  {
    iso_639_1: 'cv',
    iso_639_2: 'chv',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Chuvash',
    name: 'Чӑваш чӗлхи',
  },
  {
    iso_639_1: 'cy',
    iso_639_2: 'cym',
    iso_3166_1: 'GB',
    flag: '🇬🇧',
    english_name: 'Welsh',
    name: 'Cymraeg',
  },

  // D
  {
    iso_639_1: 'da',
    iso_639_2: 'dan',
    iso_3166_1: 'DK',
    flag: '🇩🇰',
    flag_priority: true,
    english_name: 'Danish',
    name: 'Dansk',
  },
  {
    iso_639_1: 'de',
    iso_639_2: 'deu',
    iso_3166_1: 'DE',
    flag: '🇩🇪',
    flag_priority: true,
    english_name: 'German',
    name: 'Deutsch',
  },
  {
    iso_639_1: 'dv',
    iso_639_2: 'div',
    iso_3166_1: 'MV',
    flag: '🇲🇻',
    english_name: 'Divehi',
    name: 'ދިވެހި',
  },
  {
    iso_639_1: 'dz',
    iso_639_2: 'dzo',
    iso_3166_1: 'BT',
    flag: '🇧🇹',
    english_name: 'Dzongkha',
    name: 'རྫོང་ཁ',
  },

  // E
  {
    iso_639_1: 'ee',
    iso_639_2: 'ewe',
    iso_3166_1: 'GH',
    flag: '🇬🇭',
    english_name: 'Ewe',
    name: 'Èʋegbe',
  },
  {
    iso_639_1: 'el',
    iso_639_2: 'ell',
    iso_3166_1: 'GR',
    flag: '🇬🇷',
    english_name: 'Greek',
    name: 'Ελληνικά',
  },
  {
    iso_639_1: 'en',
    iso_639_2: 'eng',
    iso_3166_1: 'GB',
    flag: '🇬🇧',
    flag_priority: true,
    english_name: 'English (UK)',
    name: 'English',
  },
  {
    iso_639_1: 'en',
    iso_639_2: 'eng',
    iso_3166_1: 'US',
    flag: '🇺🇸',
    english_name: 'English (US)',
    name: 'English',
  },
  {
    iso_639_1: 'en',
    iso_639_2: 'eng',
    iso_3166_1: 'AU',
    flag: '🇦🇺',
    english_name: 'English (Australia)',
    name: 'English',
  },
  {
    iso_639_1: 'en',
    iso_639_2: 'eng',
    iso_3166_1: 'CA',
    flag: '🇨🇦',
    english_name: 'English (Canada)',
    name: 'English',
  },
  {
    iso_639_1: 'en',
    iso_639_2: 'eng',
    iso_3166_1: 'IE',
    flag: '🇮🇪',
    english_name: 'English (Ireland)',
    name: 'English',
  },
  {
    iso_639_1: 'en',
    iso_639_2: 'eng',
    iso_3166_1: 'NZ',
    flag: '🇳🇿',
    english_name: 'English (New Zealand)',
    name: 'English',
  },
  {
    iso_639_1: 'eo',
    iso_639_2: 'epo',
    iso_3166_1: null,
    flag: '🌐',
    english_name: 'Esperanto',
    name: 'Esperanto',
  },
  {
    iso_639_1: 'es',
    iso_639_2: 'spa',
    iso_3166_1: 'ES',
    flag: '🇪🇸',
    flag_priority: true,
    english_name: 'Spanish',
    name: 'Español',
  },
  {
    iso_639_1: 'et',
    iso_639_2: 'est',
    iso_3166_1: 'EE',
    flag: '🇪🇪',
    english_name: 'Estonian',
    name: 'Eesti',
  },
  {
    iso_639_1: 'eu',
    iso_639_2: 'eus',
    iso_3166_1: 'ES',
    flag: '🏴',
    english_name: 'Basque',
    name: 'Euskera',
  },

  // F
  {
    iso_639_1: 'fa',
    iso_639_2: 'fas',
    iso_3166_1: 'IR',
    flag: '🇮🇷',
    english_name: 'Persian',
    name: 'فارسی',
  },
  {
    iso_639_1: 'ff',
    iso_639_2: 'ful',
    iso_3166_1: 'SN',
    flag: '🇸🇳',
    english_name: 'Fulah',
    name: 'Fulfulde',
  },
  {
    iso_639_1: 'fi',
    iso_639_2: 'fin',
    iso_3166_1: 'FI',
    flag: '🇫🇮',
    english_name: 'Finnish',
    name: 'Suomi',
  },
  {
    iso_639_1: 'fj',
    iso_639_2: 'fij',
    iso_3166_1: 'FJ',
    flag: '🇫🇯',
    english_name: 'Fijian',
    name: 'Vosa Vakaviti',
  },
  {
    iso_639_1: 'fo',
    iso_639_2: 'fao',
    iso_3166_1: 'FO',
    flag: '🇫🇴',
    english_name: 'Faroese',
    name: 'Føroyskt',
  },
  {
    iso_639_1: 'fr',
    iso_639_2: 'fra',
    iso_3166_1: 'FR',
    flag: '🇫🇷',
    flag_priority: true,
    english_name: 'French',
    name: 'Français',
  },
  {
    iso_639_1: 'fy',
    iso_639_2: 'fry',
    iso_3166_1: 'NL',
    flag: '🇳🇱',
    english_name: 'Western Frisian',
    name: 'Frysk',
  },

  // G
  {
    iso_639_1: 'ga',
    iso_639_2: 'gle',
    iso_3166_1: 'IE',
    flag: '🇮🇪',
    english_name: 'Irish',
    name: 'Gaeilge',
  },
  {
    iso_639_1: 'gd',
    iso_639_2: 'gla',
    iso_3166_1: 'GB',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    english_name: 'Scottish Gaelic',
    name: 'Gàidhlig',
  },
  {
    iso_639_1: 'gl',
    iso_639_2: 'glg',
    iso_3166_1: 'ES',
    flag: '🇪🇸',
    english_name: 'Galician',
    name: 'Galego',
  },
  {
    iso_639_1: 'gn',
    iso_639_2: 'grn',
    iso_3166_1: 'PY',
    flag: '🇵🇾',
    english_name: 'Guarani',
    name: "Avañe'ẽ",
  },
  {
    iso_639_1: 'gu',
    iso_639_2: 'guj',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Gujarati',
    name: 'ગુજરાતી',
  },
  {
    iso_639_1: 'gv',
    iso_639_2: 'glv',
    iso_3166_1: 'IM',
    flag: '🇮🇲',
    english_name: 'Manx',
    name: 'Gaelg',
  },

  // H
  {
    iso_639_1: 'ha',
    iso_639_2: 'hau',
    iso_3166_1: 'NG',
    flag: '🇳🇬',
    english_name: 'Hausa',
    name: 'Hausa',
  },
  {
    iso_639_1: 'he',
    iso_639_2: 'heb',
    iso_3166_1: 'IL',
    flag: '🇮🇱',
    flag_priority: true,
    english_name: 'Hebrew',
    name: 'עִבְרִית',
  },
  {
    iso_639_1: 'hi',
    iso_639_2: 'hin',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    flag_priority: true,
    english_name: 'Hindi',
    name: 'हिन्दी',
  },
  {
    iso_639_1: 'ho',
    iso_639_2: 'hmo',
    iso_3166_1: 'PG',
    flag: '🇵🇬',
    english_name: 'Hiri Motu',
    name: 'Hiri Motu',
  },
  {
    iso_639_1: 'hr',
    iso_639_2: 'hrv',
    iso_3166_1: 'HR',
    flag: '🇭🇷',
    english_name: 'Croatian',
    name: 'Hrvatski',
  },
  {
    iso_639_1: 'ht',
    iso_639_2: 'hat',
    iso_3166_1: 'HT',
    flag: '🇭🇹',
    english_name: 'Haitian; Haitian Creole',
    name: 'Kreyòl ayisyen',
  },
  {
    iso_639_1: 'hu',
    iso_639_2: 'hun',
    iso_3166_1: 'HU',
    flag: '🇭🇺',
    english_name: 'Hungarian',
    name: 'Magyar',
  },
  {
    iso_639_1: 'hy',
    iso_639_2: 'hye',
    iso_3166_1: 'AM',
    flag: '🇦🇲',
    english_name: 'Armenian',
    name: 'Հայերեն',
  },
  {
    iso_639_1: 'hz',
    iso_639_2: 'her',
    iso_3166_1: 'NA',
    flag: '🇳🇦',
    english_name: 'Herero',
    name: 'Otjiherero',
  },

  // I
  {
    iso_639_1: 'ia',
    iso_639_2: 'ina',
    iso_3166_1: null,
    flag: '🌐',
    english_name: 'Interlingua',
    name: 'Interlingua',
  },
  {
    iso_639_1: 'id',
    iso_639_2: 'ind',
    iso_3166_1: 'ID',
    flag: '🇮🇩',
    flag_priority: true,
    english_name: 'Indonesian',
    name: 'Bahasa Indonesia',
  },
  {
    iso_639_1: 'ie',
    iso_639_2: 'ile',
    iso_3166_1: null,
    flag: '🌐',
    english_name: 'Interlingue',
    name: 'Interlingue',
  },
  {
    iso_639_1: 'ig',
    iso_639_2: 'ibo',
    iso_3166_1: 'NG',
    flag: '🇳🇬',
    english_name: 'Igbo',
    name: 'Asụsụ Igbo',
  },
  {
    iso_639_1: 'ii',
    iso_639_2: 'iii',
    iso_3166_1: 'CN',
    flag: '🇨🇳',
    english_name: 'Sichuan Yi; Nuosu',
    name: 'ꆈꌠꉙ',
  },
  {
    iso_639_1: 'ik',
    iso_639_2: 'ipk',
    iso_3166_1: 'US',
    flag: '🇺🇸',
    english_name: 'Inupiaq',
    name: 'Iñupiaq',
  },
  {
    iso_639_1: 'io',
    iso_639_2: 'ido',
    iso_3166_1: null,
    flag: '🌐',
    english_name: 'Ido',
    name: 'Ido',
  },
  {
    iso_639_1: 'is',
    iso_639_2: 'isl',
    iso_3166_1: 'IS',
    flag: '🇮🇸',
    english_name: 'Icelandic',
    name: 'Íslenska',
  },
  {
    iso_639_1: 'it',
    iso_639_2: 'ita',
    iso_3166_1: 'IT',
    flag: '🇮🇹',
    flag_priority: true,
    english_name: 'Italian',
    name: 'Italiano',
  },
  {
    iso_639_1: 'iu',
    iso_639_2: 'iku',
    iso_3166_1: 'CA',
    flag: '🇨🇦',
    english_name: 'Inuktitut',
    name: 'ᐃᓄᒃᑎᑐᑦ',
  },

  // J
  {
    iso_639_1: 'ja',
    iso_639_2: 'jpn',
    iso_3166_1: 'JP',
    flag: '🇯🇵',
    english_name: 'Japanese',
    name: '日本語',
  },
  {
    iso_639_1: 'jv',
    iso_639_2: 'jav',
    iso_3166_1: 'ID',
    flag: '🇮🇩',
    english_name: 'Javanese',
    name: 'Basa Jawa',
  },

  // K
  {
    iso_639_1: 'ka',
    iso_639_2: 'kat',
    iso_3166_1: 'GE',
    flag: '🇬🇪',
    english_name: 'Georgian',
    name: 'ქართული',
  },
  {
    iso_639_1: 'kg',
    iso_639_2: 'kon',
    iso_3166_1: 'CD',
    flag: '🇨🇩',
    english_name: 'Kongo',
    name: 'KiKongo',
  },
  {
    iso_639_1: 'ki',
    iso_639_2: 'kik',
    iso_3166_1: 'KE',
    flag: '🇰🇪',
    english_name: 'Kikuyu; Gikuyu',
    name: 'Gĩkũyũ',
  },
  {
    iso_639_1: 'kj',
    iso_639_2: 'kua',
    iso_3166_1: 'AO',
    flag: '🇦🇴',
    english_name: 'Kuanyama; Kwanyama',
    name: 'Kuanyama',
  },
  {
    iso_639_1: 'kk',
    iso_639_2: 'kaz',
    iso_3166_1: 'KZ',
    flag: '🇰🇿',
    english_name: 'Kazakh',
    name: 'Қазақ',
  },
  {
    iso_639_1: 'kl',
    iso_639_2: 'kal',
    iso_3166_1: 'GL',
    flag: '🇬🇱',
    english_name: 'Kalaallisut; Greenlandic',
    name: 'Kalaallisut',
  },
  {
    iso_639_1: 'km',
    iso_639_2: 'khm',
    iso_3166_1: 'KH',
    flag: '🇰🇭',
    english_name: 'Central Khmer',
    name: 'ភាសាខ្មែរ',
  },
  {
    iso_639_1: 'kn',
    iso_639_2: 'kan',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Kannada',
    name: 'ಕನ್ನಡ',
  },
  {
    iso_639_1: 'ko',
    iso_639_2: 'kor',
    iso_3166_1: 'KR',
    flag: '🇰🇷',
    english_name: 'Korean',
    name: '한국어/조선말',
  },
  {
    iso_639_1: 'kr',
    iso_639_2: 'kau',
    iso_3166_1: 'NE',
    flag: '🇳🇪',
    english_name: 'Kanuri',
    name: 'Kanuri',
  },
  {
    iso_639_1: 'ks',
    iso_639_2: 'kas',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Kashmiri',
    name: 'कश्मीरी',
  },
  {
    iso_639_1: 'ku',
    iso_639_2: 'kur',
    iso_3166_1: 'TR',
    flag: '🇹🇷',
    english_name: 'Kurdish',
    name: 'Kurdî',
  },
  {
    iso_639_1: 'kv',
    iso_639_2: 'kom',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Komi',
    name: 'Коми кыв',
  },
  {
    iso_639_1: 'kw',
    iso_639_2: 'cor',
    iso_3166_1: 'GB',
    flag: '🇬🇧',
    english_name: 'Cornish',
    name: 'Kernewek',
  },
  {
    iso_639_1: 'ky',
    iso_639_2: 'kir',
    iso_3166_1: 'KG',
    flag: '🇰🇬',
    english_name: 'Kirghiz; Kyrgyz',
    name: 'Кыргызча',
  },

  // L
  {
    iso_639_1: 'la',
    iso_639_2: 'lat',
    iso_3166_1: 'VA',
    flag: '🇻🇦',
    english_name: 'Latin',
    name: 'Latine',
  },
  {
    iso_639_1: 'lb',
    iso_639_2: 'ltz',
    iso_3166_1: 'LU',
    flag: '🇱🇺',
    english_name: 'Luxembourgish; Letzeburgesch',
    name: 'Lëtzebuergesch',
  },
  {
    iso_639_1: 'lg',
    iso_639_2: 'lug',
    iso_3166_1: 'UG',
    flag: '🇺🇬',
    english_name: 'Ganda',
    name: 'Luganda',
  },
  {
    iso_639_1: 'li',
    iso_639_2: 'lim',
    iso_3166_1: 'NL',
    flag: '🇳🇱',
    english_name: 'Limburgan; Limburger; Limburgish',
    name: 'Limburgs',
  },
  {
    iso_639_1: 'ln',
    iso_639_2: 'lin',
    iso_3166_1: 'CD',
    flag: '🇨🇩',
    english_name: 'Lingala',
    name: 'Lingála',
  },
  {
    iso_639_1: 'lo',
    iso_639_2: 'lao',
    iso_3166_1: 'LA',
    flag: '🇱🇦',
    english_name: 'Lao',
    name: 'ພາສາລາວ',
  },
  {
    iso_639_1: 'lt',
    iso_639_2: 'lit',
    iso_3166_1: 'LT',
    flag: '🇱🇹',
    english_name: 'Lithuanian',
    name: 'Lietuvių',
  },
  {
    iso_639_1: 'lu',
    iso_639_2: 'lub',
    iso_3166_1: 'CD',
    flag: '🇨🇩',
    english_name: 'Luba-Katanga',
    name: 'Tshiluba',
  },
  {
    iso_639_1: 'lv',
    iso_639_2: 'lav',
    iso_3166_1: 'LV',
    flag: '🇱🇻',
    english_name: 'Latvian',
    name: 'Latviešu',
  },

  // M
  {
    iso_639_1: 'mg',
    iso_639_2: 'mlg',
    iso_3166_1: 'MG',
    flag: '🇲🇬',
    english_name: 'Malagasy',
    name: 'Malagasy',
  },
  {
    iso_639_1: 'mh',
    iso_639_2: 'mah',
    iso_3166_1: 'MH',
    flag: '🇲🇭',
    english_name: 'Marshallese',
    name: 'Kajin M̧ajeļ',
  },
  {
    iso_639_1: 'mi',
    iso_639_2: 'mri',
    iso_3166_1: 'NZ',
    flag: '🇳🇿',
    english_name: 'Maori',
    name: 'Te Reo Māori',
  },
  {
    iso_639_1: 'mk',
    iso_639_2: 'mkd',
    iso_3166_1: 'MK',
    flag: '🇲🇰',
    english_name: 'Macedonian',
    name: 'Македонски јазик',
  },
  {
    iso_639_1: 'ml',
    iso_639_2: 'mal',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Malayalam',
    name: 'മലയാളം',
  },
  {
    iso_639_1: 'mn',
    iso_639_2: 'mon',
    iso_3166_1: 'MN',
    flag: '🇲🇳',
    english_name: 'Mongolian',
    name: 'Монгол',
  },
  {
    iso_639_1: 'mr',
    iso_639_2: 'mar',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Marathi',
    name: 'मराठी',
  },
  {
    iso_639_1: 'ms',
    iso_639_2: 'msa',
    iso_3166_1: 'MY',
    flag: '🇲🇾',
    english_name: 'Malay',
    name: 'Bahasa Melayu',
  },
  {
    iso_639_1: 'mt',
    iso_639_2: 'mlt',
    iso_3166_1: 'MT',
    flag: '🇲🇹',
    english_name: 'Maltese',
    name: 'Malti',
  },
  {
    iso_639_1: 'my',
    iso_639_2: 'mya',
    iso_3166_1: 'MM',
    flag: '🇲🇲',
    english_name: 'Burmese',
    name: 'ဗမာစာ',
  },

  // N
  {
    iso_639_1: 'na',
    iso_639_2: 'nau',
    iso_3166_1: 'NR',
    flag: '🇳🇷',
    english_name: 'Nauru',
    name: 'Dorerin Naoero',
  },
  {
    iso_639_1: 'nb',
    iso_639_2: 'nob',
    iso_3166_1: 'NO',
    flag: '🇳🇴',
    english_name: 'Bokmål, Norwegian; Norwegian Bokmål',
    name: 'Bokmål',
  },
  {
    iso_639_1: 'nd',
    iso_639_2: 'nde',
    iso_3166_1: 'ZW',
    flag: '🇿🇼',
    english_name: 'Ndebele, North; North Ndebele',
    name: 'IsiNdebele',
  },
  {
    iso_639_1: 'ne',
    iso_639_2: 'nep',
    iso_3166_1: 'NP',
    flag: '🇳🇵',
    english_name: 'Nepali',
    name: 'नेपाली',
  },
  {
    iso_639_1: 'ng',
    iso_639_2: 'ndo',
    iso_3166_1: 'NA',
    flag: '🇳🇦',
    english_name: 'Ndonga',
    name: 'Owambo',
  },
  {
    iso_639_1: 'nl',
    iso_639_2: 'nld',
    iso_3166_1: 'NL',
    flag: '🇳🇱',
    flag_priority: true,
    english_name: 'Dutch; Flemish',
    name: 'Nederlands',
  },
  {
    iso_639_1: 'nn',
    iso_639_2: 'nno',
    iso_3166_1: 'NO',
    flag: '🇳🇴',
    english_name: 'Norwegian Nynorsk; Nynorsk, Norwegian',
    name: 'Nynorsk',
  },
  {
    iso_639_1: 'no',
    iso_639_2: 'nor',
    iso_3166_1: 'NO',
    flag: '🇳🇴',
    flag_priority: true,
    english_name: 'Norwegian',
    name: 'Norsk',
  },
  {
    iso_639_1: 'nr',
    iso_639_2: 'nbl',
    iso_3166_1: 'ZA',
    flag: '🇿🇦',
    english_name: 'Ndebele, South; South Ndebele',
    name: 'IsiNdebele',
  },
  {
    iso_639_1: 'nv',
    iso_639_2: 'nav',
    iso_3166_1: 'US',
    flag: '🇺🇸',
    english_name: 'Navajo; Navaho',
    name: 'Diné bizaad',
  },
  {
    iso_639_1: 'ny',
    iso_639_2: 'nya',
    iso_3166_1: 'MW',
    flag: '🇲🇼',
    english_name: 'Chichewa; Chewa; Nyanja',
    name: 'ChiCheŵa',
  },

  // O
  {
    iso_639_1: 'oc',
    iso_639_2: 'oci',
    iso_3166_1: 'FR',
    flag: '🇫🇷',
    english_name: 'Occitan (post 1500)',
    name: 'Occitan',
  },
  {
    iso_639_1: 'oj',
    iso_639_2: 'oji',
    iso_3166_1: 'CA',
    flag: '🇨🇦',
    english_name: 'Ojibwa',
    name: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
  },
  {
    iso_639_1: 'om',
    iso_639_2: 'orm',
    iso_3166_1: 'ET',
    flag: '🇪🇹',
    english_name: 'Oromo',
    name: 'Afaan Oromoo',
  },
  {
    iso_639_1: 'or',
    iso_639_2: 'ori',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Oriya',
    name: 'ଓଡ଼ିଆ',
  },
  {
    iso_639_1: 'os',
    iso_639_2: 'oss',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Ossetian; Ossetic',
    name: 'Ирон æвзаг',
  },

  // P
  {
    iso_639_1: 'pa',
    iso_639_2: 'pan',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Panjabi; Punjabi',
    name: 'ਪੰਜਾਬੀ',
  },
  {
    iso_639_1: 'pi',
    iso_639_2: 'pli',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Pali',
    name: 'पाऴि',
  },
  {
    iso_639_1: 'pl',
    iso_639_2: 'pol',
    iso_3166_1: 'PL',
    flag: '🇵🇱',
    english_name: 'Polish',
    name: 'Polski',
  },
  {
    iso_639_1: 'ps',
    iso_639_2: 'pus',
    iso_3166_1: 'AF',
    flag: '🇦🇫',
    english_name: 'Pushto; Pashto',
    name: 'پښتو',
  },
  {
    iso_639_1: 'pt',
    iso_639_2: 'por',
    iso_3166_1: 'PT',
    flag: '🇵🇹',
    flag_priority: true,
    english_name: 'Portuguese',
    name: 'Português',
  },
  {
    iso_639_1: 'pt',
    iso_639_2: 'por',
    iso_3166_1: 'BR',
    flag: '🇧🇷',
    english_name: 'Portuguese (Brazil)',
    name: 'Português',
  },

  // Q
  {
    iso_639_1: 'qu',
    iso_639_2: 'que',
    iso_3166_1: 'PE',
    flag: '🇵🇪',
    english_name: 'Quechua',
    name: 'Runa Simi',
  },

  // R
  {
    iso_639_1: 'rm',
    iso_639_2: 'roh',
    iso_3166_1: 'CH',
    flag: '🇨🇭',
    english_name: 'Romansh',
    name: 'Rumantsch grischun',
  },
  {
    iso_639_1: 'rn',
    iso_639_2: 'run',
    iso_3166_1: 'BI',
    flag: '🇧🇮',
    english_name: 'Rundi',
    name: 'Kirundi',
  },
  {
    iso_639_1: 'ro',
    iso_639_2: 'ron',
    iso_3166_1: 'RO',
    flag: '🇷🇴',
    english_name: 'Romanian; Moldavian; Moldovan',
    name: 'Română',
  },
  {
    iso_639_1: 'ru',
    iso_639_2: 'rus',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    flag_priority: true,
    english_name: 'Russian',
    name: 'Pусский',
  },
  {
    iso_639_1: 'rw',
    iso_639_2: 'kin',
    iso_3166_1: 'RW',
    flag: '🇷🇼',
    english_name: 'Kinyarwanda',
    name: 'Ikinyarwanda',
  },

  // S
  {
    iso_639_1: 'sa',
    iso_639_2: 'san',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Sanskrit',
    name: 'संस्कृतम्',
  },
  {
    iso_639_1: 'sc',
    iso_639_2: 'srd',
    iso_3166_1: 'IT',
    flag: '🇮🇹',
    english_name: 'Sardinian',
    name: 'Sardu',
  },
  {
    iso_639_1: 'sd',
    iso_639_2: 'snd',
    iso_3166_1: 'PK',
    flag: '🇵🇰',
    english_name: 'Sindhi',
    name: 'सिन्धी',
  },
  {
    iso_639_1: 'se',
    iso_639_2: 'sme',
    iso_3166_1: 'NO',
    flag: '🇳🇴',
    english_name: 'Northern Sami',
    name: 'Davvisámegiella',
  },
  {
    iso_639_1: 'sg',
    iso_639_2: 'sag',
    iso_3166_1: 'CF',
    flag: '🇨🇫',
    english_name: 'Sango',
    name: 'Yângâ tî sängö',
  },
  {
    iso_639_1: 'sh',
    iso_639_2: 'hbs',
    iso_3166_1: 'RS',
    flag: '🇷🇸',
    english_name: 'Serbo-Croatian',
    name: 'Srpskohrvatski',
  },
  {
    iso_639_1: 'si',
    iso_639_2: 'sin',
    iso_3166_1: 'LK',
    flag: '🇱🇰',
    english_name: 'Sinhala; Sinhalese',
    name: 'සිංහල',
  },
  {
    iso_639_1: 'sk',
    iso_639_2: 'slk',
    iso_3166_1: 'SK',
    flag: '🇸🇰',
    flag_priority: true,
    english_name: 'Slovak',
    name: 'Slovenčina',
  },
  {
    iso_639_1: 'sl',
    iso_639_2: 'slv',
    iso_3166_1: 'SI',
    flag: '🇸🇮',
    english_name: 'Slovenian',
    name: 'Slovenščina',
  },
  {
    iso_639_1: 'sm',
    iso_639_2: 'smo',
    iso_3166_1: 'WS',
    flag: '🇼🇸',
    english_name: 'Samoan',
    name: "Gagana fa'a Samoa",
  },
  {
    iso_639_1: 'sn',
    iso_639_2: 'sna',
    iso_3166_1: 'ZW',
    flag: '🇿🇼',
    english_name: 'Shona',
    name: 'ChiShona',
  },
  {
    iso_639_1: 'so',
    iso_639_2: 'som',
    iso_3166_1: 'SO',
    flag: '🇸🇴',
    english_name: 'Somali',
    name: 'Af Soomaali',
  },
  {
    iso_639_1: 'sq',
    iso_639_2: 'sqi',
    iso_3166_1: 'AL',
    flag: '🇦🇱',
    english_name: 'Albanian',
    name: 'Shqip',
  },
  {
    iso_639_1: 'sr',
    iso_639_2: 'srp',
    iso_3166_1: 'RS',
    flag: '🇷🇸',
    flag_priority: true,
    english_name: 'Serbian',
    name: 'Srpski',
  },
  {
    iso_639_1: 'ss',
    iso_639_2: 'ssw',
    iso_3166_1: 'SZ',
    flag: '🇸🇿',
    english_name: 'Swati',
    name: 'SiSwati',
  },
  {
    iso_639_1: 'st',
    iso_639_2: 'sot',
    iso_3166_1: 'LS',
    flag: '🇱🇸',
    english_name: 'Sotho, Southern',
    name: 'Sesotho',
  },
  {
    iso_639_1: 'su',
    iso_639_2: 'sun',
    iso_3166_1: 'ID',
    flag: '🇮🇩',
    english_name: 'Sundanese',
    name: 'Basa Sunda',
  },
  {
    iso_639_1: 'sv',
    iso_639_2: 'swe',
    iso_3166_1: 'SE',
    flag: '🇸🇪',
    english_name: 'Swedish',
    name: 'Svenska',
  },
  {
    iso_639_1: 'sw',
    iso_639_2: 'swa',
    iso_3166_1: 'KE',
    flag: '🇰🇪',
    english_name: 'Swahili',
    name: 'Kiswahili',
  },

  // T
  {
    iso_639_1: 'ta',
    iso_639_2: 'tam',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Tamil',
    name: 'தமிழ்',
  },
  {
    iso_639_1: 'te',
    iso_639_2: 'tel',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Telugu',
    name: 'తెలుగు',
  },
  {
    iso_639_1: 'tg',
    iso_639_2: 'tgk',
    iso_3166_1: 'TJ',
    flag: '🇹🇯',
    english_name: 'Tajik',
    name: 'тоҷикӣ',
  },
  {
    iso_639_1: 'th',
    iso_639_2: 'tha',
    iso_3166_1: 'TH',
    flag: '🇹🇭',
    english_name: 'Thai',
    name: 'ภาษาไทย',
  },
  {
    iso_639_1: 'ti',
    iso_639_2: 'tir',
    iso_3166_1: 'ER',
    flag: '🇪🇷',
    english_name: 'Tigrinya',
    name: 'ትግርኛ',
  },
  {
    iso_639_1: 'tk',
    iso_639_2: 'tuk',
    iso_3166_1: 'TM',
    flag: '🇹🇲',
    english_name: 'Turkmen',
    name: 'Türkmen',
  },
  {
    iso_639_1: 'tl',
    iso_639_2: 'tgl',
    iso_3166_1: 'PH',
    flag: '🇵🇭',
    english_name: 'Tagalog',
    name: 'Wikang Tagalog',
  },
  {
    iso_639_1: 'tn',
    iso_639_2: 'tsn',
    iso_3166_1: 'BW',
    flag: '🇧🇼',
    english_name: 'Tswana',
    name: 'Setswana',
  },
  {
    iso_639_1: 'to',
    iso_639_2: 'ton',
    iso_3166_1: 'TO',
    flag: '🇹🇴',
    english_name: 'Tonga (Tonga Islands)',
    name: 'Faka Tonga',
  },
  {
    iso_639_1: 'tr',
    iso_639_2: 'tur',
    iso_3166_1: 'TR',
    flag: '🇹🇷',
    english_name: 'Turkish',
    name: 'Türkçe',
  },
  {
    iso_639_1: 'ts',
    iso_639_2: 'tso',
    iso_3166_1: 'ZA',
    flag: '🇿🇦',
    english_name: 'Tsonga',
    name: 'Xitsonga',
  },
  {
    iso_639_1: 'tt',
    iso_639_2: 'tat',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Tatar',
    name: 'Татар теле',
  },
  {
    iso_639_1: 'tw',
    iso_639_2: 'twi',
    iso_3166_1: 'GH',
    flag: '🇬🇭',
    english_name: 'Twi',
    name: 'Twi',
  },
  {
    iso_639_1: 'ty',
    iso_639_2: 'tah',
    iso_3166_1: 'PF',
    flag: '🇵🇫',
    english_name: 'Tahitian',
    name: 'Reo Tahiti',
  },

  // U
  {
    iso_639_1: 'ug',
    iso_639_2: 'uig',
    iso_3166_1: 'CN',
    flag: '🇨🇳',
    english_name: 'Uighur; Uyghur',
    name: 'Uyƣurqə',
  },
  {
    iso_639_1: 'uk',
    iso_639_2: 'ukr',
    iso_3166_1: 'UA',
    flag: '🇺🇦',
    english_name: 'Ukrainian',
    name: 'Український',
  },
  {
    iso_639_1: 'ur',
    iso_639_2: 'urd',
    iso_3166_1: 'PK',
    flag: '🇵🇰',
    english_name: 'Urdu',
    name: 'اردو',
  },
  {
    iso_639_1: 'uz',
    iso_639_2: 'uzb',
    iso_3166_1: 'UZ',
    flag: '🇺🇿',
    english_name: 'Uzbek',
    name: 'Oʻzbek',
  },

  // V
  {
    iso_639_1: 've',
    iso_639_2: 'ven',
    iso_3166_1: 'ZA',
    flag: '🇿🇦',
    english_name: 'Venda',
    name: 'Tshivenḓa',
  },
  {
    iso_639_1: 'vi',
    iso_639_2: 'vie',
    iso_3166_1: 'VN',
    flag: '🇻🇳',
    english_name: 'Vietnamese',
    name: 'Tiếng Việt',
  },
  {
    iso_639_1: 'vo',
    iso_639_2: 'vol',
    iso_3166_1: null,
    flag: '🌐',
    english_name: 'Volapük',
    name: 'Volapük',
  },

  // W
  {
    iso_639_1: 'wa',
    iso_639_2: 'wln',
    iso_3166_1: 'BE',
    flag: '🇧🇪',
    english_name: 'Walloon',
    name: 'Walon',
  },
  {
    iso_639_1: 'wo',
    iso_639_2: 'wol',
    iso_3166_1: 'SN',
    flag: '🇸🇳',
    english_name: 'Wolof',
    name: 'Wolof',
  },

  // X
  {
    iso_639_1: 'xh',
    iso_639_2: 'xho',
    iso_3166_1: 'ZA',
    flag: '🇿🇦',
    english_name: 'Xhosa',
    name: 'IsiXhosa',
  },

  // Y
  {
    iso_639_1: 'yi',
    iso_639_2: 'yid',
    iso_3166_1: 'IL',
    flag: '🇮🇱',
    english_name: 'Yiddish',
    name: 'ייִדיש',
  },
  {
    iso_639_1: 'yo',
    iso_639_2: 'yor',
    iso_3166_1: 'NG',
    flag: '🇳🇬',
    english_name: 'Yoruba',
    name: 'Èdè Yorùbá',
  },

  // Z
  {
    iso_639_1: 'za',
    iso_639_2: 'zha',
    iso_3166_1: 'CN',
    flag: '🇨🇳',
    english_name: 'Zhuang; Chuang',
    name: 'Saɯ cueŋƅ',
  },
  {
    iso_639_1: 'zh',
    iso_639_2: 'zho',
    iso_3166_1: 'CN',
    flag: '🇨🇳',
    flag_priority: true,
    english_name: 'Chinese (Simplified)',
    name: '中文 (简体)',
  },

  {
    iso_639_1: 'zh',
    iso_639_2: 'zho',
    iso_3166_1: 'TW',
    flag: '🇹🇼',
    english_name: 'Chinese (Traditional)',
    name: '中文 (繁體)',
  },
  {
    iso_639_1: 'zh',
    iso_639_2: 'zho',
    iso_3166_1: 'HK',
    flag: '🇭🇰',
    english_name: 'Chinese (Hong Kong)',
    name: '中文 (香港)',
  },
  {
    iso_639_1: 'zh',
    iso_639_2: 'zho',
    iso_3166_1: 'SG',
    flag: '🇸🇬',
    english_name: 'Chinese (Singapore)',
    name: '中文 (新加坡)',
  },
  {
    iso_639_1: 'zu',
    iso_639_2: 'zul',
    iso_3166_1: 'ZA',
    flag: '🇿🇦',
    english_name: 'Zulu',
    name: 'IsiZulu',
  },

  // Additional languages not in your original list but commonly used
  {
    iso_639_1: 'sw',
    iso_639_2: 'swa',
    iso_3166_1: 'TZ',
    flag: '🇹🇿',
    english_name: 'Swahili (Tanzania)',
    name: 'Kiswahili',
  },
  {
    iso_639_1: 'fr',
    iso_639_2: 'fra',
    iso_3166_1: 'CA',
    flag: '🇨🇦',
    english_name: 'French (Canada)',
    name: 'Français',
  },
  {
    iso_639_1: 'fr',
    iso_639_2: 'fra',
    iso_3166_1: 'BE',
    flag: '🇧🇪',
    english_name: 'French (Belgium)',
    name: 'Français',
  },
  {
    iso_639_1: 'fr',
    iso_639_2: 'fra',
    iso_3166_1: 'CH',
    flag: '🇨🇭',
    english_name: 'French (Switzerland)',
    name: 'Français',
  },
  {
    iso_639_1: 'de',
    iso_639_2: 'deu',
    iso_3166_1: 'AT',
    flag: '🇦🇹',
    english_name: 'German (Austria)',
    name: 'Deutsch',
  },
  {
    iso_639_1: 'de',
    iso_639_2: 'deu',
    iso_3166_1: 'CH',
    flag: '🇨🇭',
    english_name: 'German (Switzerland)',
    name: 'Deutsch',
  },
  {
    iso_639_1: 'it',
    iso_639_2: 'ita',
    iso_3166_1: 'CH',
    flag: '🇨🇭',
    english_name: 'Italian (Switzerland)',
    name: 'Italiano',
  },
  {
    iso_639_1: 'es',
    iso_639_2: 'spa',
    iso_3166_1: 'MX',
    flag: '🇲🇽',
    english_name: 'Spanish (Mexico)',
    internal_english_name: 'Latino',
    name: 'Español',
  },
  {
    iso_639_1: 'es',
    iso_639_2: 'spa',
    iso_3166_1: 'AR',
    flag: '🇦🇷',
    english_name: 'Spanish (Argentina)',
    name: 'Español',
  },
  {
    iso_639_1: 'es',
    iso_639_2: 'spa',
    iso_3166_1: 'CO',
    flag: '🇨🇴',
    english_name: 'Spanish (Colombia)',
    name: 'Español',
  },
  {
    iso_639_1: 'es',
    iso_639_2: 'spa',
    iso_3166_1: 'CL',
    flag: '🇨🇱',
    english_name: 'Spanish (Chile)',
    name: 'Español',
  },
  {
    iso_639_1: 'es',
    iso_639_2: 'spa',
    iso_3166_1: 'PE',
    flag: '🇵🇪',
    english_name: 'Spanish (Peru)',
    name: 'Español',
  },
  {
    iso_639_1: 'es',
    iso_639_2: 'spa',
    iso_3166_1: 'VE',
    flag: '🇻🇪',
    english_name: 'Spanish (Venezuela)',
    name: 'Español',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'MA',
    flag: '🇲🇦',
    english_name: 'Arabic (Morocco)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'DZ',
    flag: '🇩🇿',
    english_name: 'Arabic (Algeria)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'TN',
    flag: '🇹🇳',
    english_name: 'Arabic (Tunisia)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'LY',
    flag: '🇱🇾',
    english_name: 'Arabic (Libya)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'JO',
    flag: '🇯🇴',
    english_name: 'Arabic (Jordan)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'SY',
    flag: '🇸🇾',
    english_name: 'Arabic (Syria)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'LB',
    flag: '🇱🇧',
    english_name: 'Arabic (Lebanon)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'IQ',
    flag: '🇮🇶',
    english_name: 'Arabic (Iraq)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'KW',
    flag: '🇰🇼',
    english_name: 'Arabic (Kuwait)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'BH',
    flag: '🇧🇭',
    english_name: 'Arabic (Bahrain)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'QA',
    flag: '🇶🇦',
    english_name: 'Arabic (Qatar)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'OM',
    flag: '🇴🇲',
    english_name: 'Arabic (Oman)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'YE',
    flag: '🇾🇪',
    english_name: 'Arabic (Yemen)',
    name: 'العربية',
  },
  {
    iso_639_1: 'ar',
    iso_639_2: 'ara',
    iso_3166_1: 'SD',
    flag: '🇸🇩',
    english_name: 'Arabic (Sudan)',
    name: 'العربية',
  },

  // Languages without ISO 639-1 codes but with ISO 639-2 codes
  {
    iso_639_1: null,
    iso_639_2: 'ace',
    iso_3166_1: 'ID',
    flag: '🇮🇩',
    english_name: 'Achinese',
    name: 'Bahsa Acèh',
  },
  {
    iso_639_1: null,
    iso_639_2: 'ach',
    iso_3166_1: 'UG',
    flag: '🇺🇬',
    english_name: 'Acoli',
    name: 'Lwo',
  },
  {
    iso_639_1: null,
    iso_639_2: 'ada',
    iso_3166_1: 'GH',
    flag: '🇬🇭',
    english_name: 'Adangme',
    name: 'Adangme',
  },
  {
    iso_639_1: null,
    iso_639_2: 'ady',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Adyghe; Adygei',
    name: 'Адыгэбзэ',
  },
  {
    iso_639_1: null,
    iso_639_2: 'afa',
    iso_3166_1: 'ET',
    flag: '🇪🇹',
    english_name: 'Afro-Asiatic languages',
    name: 'Afro-Asiatic',
  },
  {
    iso_639_1: null,
    iso_639_2: 'afh',
    iso_3166_1: 'GH',
    flag: '🇬🇭',
    english_name: 'Afrihili',
    name: 'Afrihili',
  },
  {
    iso_639_1: null,
    iso_639_2: 'agq',
    iso_3166_1: 'CM',
    flag: '🇨🇲',
    english_name: 'Aghem',
    name: 'Aghem',
  },
  {
    iso_639_1: null,
    iso_639_2: 'ain',
    iso_3166_1: 'JP',
    flag: '🇯🇵',
    english_name: 'Ainu',
    name: 'アイヌ イタㇰ',
  },
  {
    iso_639_1: null,
    iso_639_2: 'akk',
    iso_3166_1: 'IQ',
    flag: '🇮🇶',
    english_name: 'Akkadian',
    name: 'Akkadian',
  },
  {
    iso_639_1: null,
    iso_639_2: 'ale',
    iso_3166_1: 'US',
    flag: '🇺🇸',
    english_name: 'Aleut',
    name: 'Unangam Tunuu',
  },
  {
    iso_639_1: null,
    iso_639_2: 'alt',
    iso_3166_1: 'RU',
    flag: '🇷🇺',
    english_name: 'Southern Altai',
    name: 'Алтай тил',
  },
  {
    iso_639_1: null,
    iso_639_2: 'ang',
    iso_3166_1: 'GB',
    flag: '🇬🇧',
    english_name: 'English, Old (ca.450-1100)',
    name: 'Englisc',
  },
  {
    iso_639_1: null,
    iso_639_2: 'anp',
    iso_3166_1: 'IN',
    flag: '🇮🇳',
    english_name: 'Angika',
    name: 'अंगिका',
  },
  {
    iso_639_1: null,
    iso_639_2: 'arc',
    iso_3166_1: 'SY',
    flag: '🇸🇾',
    english_name: 'Aramaic',
    name: 'ܐܪܡܝܐ',
  },
  {
    iso_639_1: null,
    iso_639_2: 'arn',
    iso_3166_1: 'CL',
    flag: '🇨🇱',
    english_name: 'Mapudungun; Mapuche',
    name: 'Mapudungun',
  },
  {
    iso_639_1: null,
    iso_639_2: 'arp',
    iso_3166_1: 'US',
    flag: '🇺🇸',
    english_name: 'Arapaho',
    name: 'Hinónoʼeitíít',
  },
  {
    iso_639_1: null,
    iso_639_2: 'arw',
    iso_3166_1: 'GY',
    flag: '🇬🇾',
    english_name: 'Arawak',
    name: 'Arawak',
  },
  {
    iso_639_1: null,
    iso_639_2: 'ast',
    iso_3166_1: 'ES',
    flag: '🇪🇸',
    english_name: 'Asturian; Bable; Leonese; Asturleonese',
    name: 'Asturianu',
  },
];
